#!/bin/bash

if [ $(cat /etc/passwd | grep "$FTP_USER:" | wc -l) -eq 0 ];then
	if [ ! -d "/home/$FTP_USER" ]; then
		useradd -ms /bin/bash $FTP_USER
		adduser $FTP_USER sftponly
	else
		useradd -Ms /bin/bash $FTP_USER
		adduser $FTP_USER sftponly
	fi
fi

if [ ! -d "/home/$FTP_USER/.ssh" ]; then
	su $FTP_USER -c "mkdir /home/$FTP_USER/.ssh"
fi

if [ ! -f "/home/$FTP_USER/.ssh/authorized_keys" ]; then
	su $FTP_USER -c "touch /home/$FTP_USER/.ssh/authorized_keys"
fi

if [[ $HAVE_INITIALIZED == false ]]; then
	/bin/rm -v /etc/ssh/ssh_host_*
	dpkg-reconfigure openssh-server
fi
